<?php

/**
 * Plugin Name: Image Convert WebP
 * Plugin URI: https://teck-global.com/wordpress-plugins/
 * Description: WordPress image resize - convert jpg/jpeg/png to WebP.
 * Author: TeckGlobal
 * Version: 1.3
 * Author URI: http://teck-global.com
 * Convert uploaded images to WebP without breaking WordPress image sizes.
 * This plugin will convert all new images from .jpg/jpeg to WebP
 * 
 */

if (!defined('ABSPATH')) {
    // Avoid direct calls to this file and prevent full path disclosure
    exit();
}

function convert_images_to_webp($file) {
    // Check if Imagick is available
    if (!class_exists('Imagick')) {
        return $file;
    }

    // Allowed image types
    $supported_types = ['image/jpeg', 'image/jpg', 'image/png'];

    // If the file is not a supported type, return it as-is
    if (!in_array($file['type'], $supported_types)) {
        return $file;
    }

    // Get the upload directory info
    $wp_upload_dir = wp_upload_dir();
    $original_file_path = $file['file'];
    $file_name = pathinfo($original_file_path, PATHINFO_FILENAME);
    $webp_file_path = trailingslashit($wp_upload_dir['path']) . $file_name . '.webp';

    // Check if the image is already WebP
    if (pathinfo($original_file_path, PATHINFO_EXTENSION) === 'webp') {
        return $file;
    }

    // Create WebP version using Imagick
    try {
        $image = new Imagick($original_file_path);
        $image->setImageFormat('webp');
        $image->setImageCompressionQuality(75); // Adjust quality as needed
        $image->stripImage(); // Remove metadata for smaller size
        $image->writeImage($webp_file_path);
        $image->clear();
        $image->destroy();
    } catch (Exception $e) {
        return $file; // If conversion fails, return original file
    }

    // Get all image sizes generated by WordPress
    $attachment_id = attachment_url_to_postid($file['url']);
    $metadata = wp_generate_attachment_metadata($attachment_id, $webp_file_path);
    wp_update_attachment_metadata($attachment_id, $metadata);

    // Return new WebP file info
    return [
        'file' => $webp_file_path,
        'url' => trailingslashit($wp_upload_dir['url']) . basename($webp_file_path),
        'type' => 'image/webp',
    ];
}

// Apply filter to all uploaded images
add_filter('wp_handle_upload', 'convert_images_to_webp');
